//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement_SIT0330.Models.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KajalPatel_SIT0330Entities : DbContext
    {
        public KajalPatel_SIT0330Entities()
            : base("name=KajalPatel_SIT0330Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Standard> Standards { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
        public virtual DbSet<Teacher1> Teacher1Set { get; set; }
    }
}
