//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice_Reppository_Pattern.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponCodeMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CouponCodeMaster()
        {
            this.order = new HashSet<order>();
        }
    
        public int CouponId { get; set; }
        public string CouponCode { get; set; }
        public int CouponType { get; set; }
        public Nullable<int> CouponFlatAmount { get; set; }
        public Nullable<int> CouponPercentage { get; set; }
        public System.DateTime CouponExpiryDate { get; set; }
        public int CouponUsageLimit { get; set; }
        public int CouponIsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order { get; set; }
    }
}
