//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice_Reppository_Pattern.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int OrderId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> couponCode { get; set; }
        public Nullable<int> itemId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<int> OrderTotalQuantity { get; set; }
        public Nullable<decimal> orderAmount { get; set; }
        public Nullable<decimal> AfterGST { get; set; }
        public Nullable<decimal> TotalPayable { get; set; }
        public Nullable<int> SGST { get; set; }
        public Nullable<int> CGST { get; set; }
    
        public virtual CouponCodeMaster CouponCodeMaster { get; set; }
        public virtual LoginInformation LoginInformation { get; set; }
    }
}
