//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Order.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KajalPatelEntities : DbContext
    {
        public KajalPatelEntities()
            : base("name=KajalPatelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<FoodList> FoodLists { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public object Teacher_Validation { get; internal set; }
    }
}
